Repository API-Guild/greenlight, pull requests merged in 2021-05, with the labels that each got.

#56 Explore
  gatsby-config.js
  package-lock.json
  package.json
  src/assets/styles/global.scss
  src/components/auth/auth.js
  src/components/dropdown/dropdown.js
  src/components/navbar/navbar.js
  src/components/search/search.js
  src/pages/explore.js
Labels: enhancement

#68 Tableau Optimizations, Explore improvements
  content/blog/elements/elements.md
  content/blog/sample-mdx/sample-mdx.mdx
  gatsby-config.js
  src/assets/styles/global.scss
  src/components/bulmaElements/bulmaElements.js
  src/components/contentIndex/contentIndex.js
  src/components/menu/menu.js
  src/components/menuList/menuList.js
  src/components/navbar/navbar.js
  src/components/search/search.js
  src/components/tableau/tableau.js
  src/pages/contact.js
  src/pages/explore.js
  static/svg/greenlight.svg
Labels: documentation, enhancement, tableau

#70 Contact and About pages
  README.md
  content/blog/elements/elements.md
  content/blog/quick-start/greenlight-sideways.png
  content/blog/quick-start/quick-start.mdx
  content/blog/sample-mdx/sample-mdx.mdx
  docs/gatsby-instructions.md
  docs/images/greenlight.jpeg
  docs/images/greenlight_image.png
  gatsby-config.js
  package-lock.json
  package.json
  src/assets/images/greenlight-sideways.jpg
  src/assets/images/greenlight-sideways.png
  src/assets/images/greenlight.jpg
  src/assets/styles/global.scss
  src/components/contactForm/contactForm.js
  src/components/contentIndex/contentIndex.js
  src/components/footer/footer.js
  src/components/search/search.js
  src/pages/about.js
  src/pages/contact.js
  src/pages/explore.js
  static/images/greenlight-sideways.jpg
  static/images/greenlight-sideways.png
  static/images/greenlight.jpg
  static/images/greenlight.png
Labels: documentation, enhancement

#72 removed purge-css as it was bugging out on table styling
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/pages/about.js
Labels: bug

#73 Themes
  src/assets/styles/global.scss
Labels: enhancement
