Repository API-Guild/greenlight, pull requests merged in 2021-04, with the labels that each got.

#8 Layout
  README.md
  docs/gatsby-instructions.md
  docs/images/greenlight.jpeg
  gatsby-browser.js
  gatsby-config.js
  package-lock.json
  package.json
  src/components/footer/footer.js
  src/components/header/header.js
  src/components/layout/layout.js
  src/pages/about/about.js
  src/pages/contact/contact.js
  src/pages/global.scss
  src/pages/index.js
Labels: enhancement

#12 Collapsible Menu and Image/SVG testing
  gatsby-config.js
  src/assets/svg/undraw_light_the_fire_gt58.svg
  src/assets/svg/undraw_lightbulb_moment_evxr.svg
  src/assets/svg/undraw_new_ideas_jdea.svg
  src/assets/svg/undraw_searching_p5ux.svg
  src/assets/svg/undraw_starry_window_ppm0.svg
  src/components/footer/footer.js
  src/components/header/header.js
  src/pages/global.scss
  src/pages/index.js
Labels: enhancement

#17 Trevors branch
  gatsby-node.js
  package-lock.json
  package.json
  src/templates/data-table-post.js
Labels: enhancement

#20 Trevors branch
  content/blog/test/test.md
  gatsby-config.js
  gatsby-node.js
  src/components/navbar/navbar.js
  src/pages/index.js
  src/templates/data-table-post.js
Labels: enhancement

#23 Components
  content/blog/test2/test2.md
  gatsby-node.js
  src/components/footer/footer.js
  src/components/navbar/navbar.js
  src/pages/dashboards.js
  src/pages/global.scss
  src/templates/post-template.js
Labels: enhancement

#26 Components
  content/blog/hello-world/hello-world.md
  content/blog/hello-world/salty_egg.jpg
  content/blog/test/test.md
  src/components/hero/hero.js
  src/pages/about.js
  src/pages/contact.js
  src/pages/dashboards.js
  src/pages/global.scss
  src/pages/index.js
  src/templates/post-template.js
Labels: enhancement

#28 Components - React Helmet
  content/blog/new-beginnings/new-beginnings.md
  content/blog/test2/test2.md
  gatsby-config.js
  package-lock.json
  package.json
  src/assets/ico/greenlight.ico
  src/components/layout/layout.js
  src/components/seo/seo.js
  src/components/tableau/tableau.js
  src/pages/index.js
Labels: enhancement

#29 Fix/markdown styles
  package-lock.json
  package.json
  src/templates/post-template.js
Labels: enhancement

#32 Installs gatsby-remark-prismjs To Enhance Code Styles.
  gatsby-browser.js
  gatsby-config.js
  package-lock.json
  package.json
Labels: enhancement

#33 Mdx
  content/blog/hello-world/hello-world.md
  content/blog/mdx-test/mdx-test.mdx
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/assets/images/greenlight.png
  src/components/layout/layout.js
  src/components/navbar/navbar.js
  src/components/tableau/tableau.js
  src/pages/dashboards.js
  src/templates/post-template.js
Labels: enhancement

#35 Mdx
  content/blog/code-blocks/code-blocks.md
  src/components/bulmaElements/bulmaElements.js
  src/templates/post-template.js
Labels: enhancement

#37 Tableau
  content/blog/code-blocks/code-blocks.md
  content/blog/mdx-test/mdx-test.mdx
  gatsby-browser.js
  package-lock.json
  package.json
  src/assets/styles/global.scss
  src/components/layout/layout.js
  src/components/navbar/navbar.js
  src/components/tableau/tableau.css
  src/components/tableau/tableau.js
  src/pages/dashboards.js
  src/templates/post-template.js
Labels: enhancement

#44 Tableau Embed Bug Fix
  content/blog/mdx-test/mdx-test.mdx
  src/components/layout/layout.js
  src/components/tableau/tableau.js
Labels: bug

#49 Embed
  content/blog/mdx-test/mdx-test.mdx
  src/assets/styles/global.scss
  src/components/tableau/tableau.css
  src/components/tableau/tableau.js
Labels: enhancement

#50 Readme
  README.md
  docs/images/greenlight_image.png
Labels: documentation

#51 Quick start
  content/blog/hello-world/hello-world.md
  content/blog/quick-start/greenlight.jpg
  content/blog/quick-start/quick-start.mdx
  gatsby-config.js
  package-lock.json
  package.json
  src/components/bulmaElements/bulmaElements.js
  src/templates/post-template.js
Labels: documentation

#54 added sample articles to the starter
  content/blog/code-blocks/code-blocks.md
  content/blog/elements/elements.md
  content/blog/elements/salty_egg.jpg
  content/blog/new-beginnings/new-beginnings.md
  content/blog/production-report/production-report.mdx
  content/blog/quarterly-cashflow/quarterly-cashflow.mdx
  content/blog/quick-start/greenlight-sideways.jpg
  content/blog/quick-start/greenlight.jpg
  content/blog/quick-start/quick-start.mdx
  content/blog/sample-mdx/sample-mdx.mdx
  content/blog/the-beatles/the-beatles.mdx
  gatsby-config.js
  src/components/tableau/tableau.js
  src/templates/post-template.js
Labels: documentation, enhancement
